version: '3.7'
services:
  jochre3-dla:
    image: registry.gitlab.com/jochre/jochre3-dla-server:1.0.5
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    
