version: "3.7"
services:
  jochre3-ocr:
    image: registry.gitlab.com/jochre/jochre3-ocr:1.1.0
    command: -Dconfig.file=/opt/docker/etc/jochre.conf
    ports:
      - 3434:3434
    volumes:
      - ./jochre.conf:/opt/docker/etc/jochre.conf
    environment:
      DOCUMENT_LAYOUT_ANALYSIS_URL: http://jochre3-dla:8444
      JOCHRE3_OCR_VERSION: 1.1.0
      JOCHRE3_OCR_DIRECTORY: /opt/docker
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    restart: on-failure
  jochre3-dla:
    image: registry.gitlab.com/jochre/jochre3-dla-server:1.0.5
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    restart: on-failure
