version: '3.7'
services:
  jochre3-ocr:
    image: registry.gitlab.com/jochre/jochre3-ocr:0.3.23
    command: -Dconfig.file=/opt/docker/etc/jochre.conf
    ports:
      - 3434:3434
    volumes:
      - ./jochre.conf:/opt/docker/etc/jochre.conf
    environment:
      DOCUMENT_LAYOUT_ANALYSIS_URL: http://yolo-dla:8444
      JOCHRE3_OCR_VERSION: 0.3.23
      JOCHRE3_OCR_DIRECTORY: /opt/docker
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    restart: on-failure
  yolo-dla:
    image: registry.gitlab.com/jochre/yolo-dla-server:1.0.4
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    restart: on-failure